<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>CreaCprjMontante</AssemblyName>
    <RootNamespace>CreaCprjMontante</RootNamespace>
    <Version>2.1.1</Version>
    <AssemblyVersion>2.1.1.0</AssemblyVersion>
    <FileVersion>2.1.1.0</FileVersion>
    <InformationalVersion>2.1.1-label-bcu-full-text</InformationalVersion>
  </PropertyGroup>
</Project>
